/**
 * Paced loader for channel logos, with a fallback route for image hosts that
 * refuse to serve TVs.
 *
 * ---- Why this exists ----
 *
 * Practically every logo in the fiberplus playlist is hosted on imgur, and
 * imgur answers any request whose User-Agent contains `SmartTV` with 429 Too
 * Many Requests — no image bytes at all. That token is part of the User-Agent
 * every LG set sends (`Mozilla/5.0 (Web0S; Linux/SmartTV) ...`), and a page
 * cannot change its own User-Agent, so a direct <img> to imgur can never
 * succeed on this platform. Verified by sending byte-identical requests that
 * differ only in that header: desktop UA -> 200 + PNG, TV UA -> 429 + empty.
 *
 * This is not a CORS problem, and CORS headers would not help: an <img> is a
 * no-cors request that renders cross-origin images without any permission
 * from the remote host. The failure happens before that — the response
 * carries no image at all.
 *
 * ---- Why the User-Agent is not simply overridden ----
 *
 * `User-Agent` is no longer a forbidden header name in Fetch, so in principle
 * the image could be pulled with fetch() under a desktop UA and handed to the
 * <img> as an object URL. It does not work here, for two independent reasons,
 * both measured against imgur rather than assumed:
 *
 *   1. Sending any non-safelisted header cross-origin forces a CORS preflight,
 *      and imgur's OPTIONS response lists exactly which headers it accepts —
 *      Authorization, Content-Type, Accept, Range and two of its own. There is
 *      no `User-Agent` in that list, so the browser rejects the request before
 *      it is ever sent.
 *   2. The preflight is generated by the browser, which stamps it with the
 *      real UA. From a TV that OPTIONS is itself answered 429, so the exchange
 *      fails at the first step regardless.
 *
 * LG's own webOSTV.js only ever reads navigator.userAgent; the platform
 * exposes no way to change it. A TV cannot claim to be anything else, so the
 * request has to be made by something that genuinely is not a TV.
 *
 * Bundling the logos with the app was the other option, and was rejected
 * because the channel providers rotate these URLs periodically; a shipped
 * copy would drift out of date and new channels would never get a logo.
 *
 * ---- Swapping the CDN ----
 *
 * Only the two constants below decide where a blocked logo is re-fetched
 * from. Point them at your own proxy — anything that takes a URL and returns
 * the image bytes — if you would rather not depend on a third party; nothing
 * else in the app needs to change.
 *
 * ---- How it works ----
 *
 * A logo is always tried at its real URL first, so hosts that behave normally
 * cost nothing extra and keep working if imgur ever lifts the block. When
 * that fails the logo is retried through an image CDN that fetches it
 * server-side and re-serves it (already downscaled, which is a bonus on a
 * panel where a tile is ~240px wide). After a few direct failures from the
 * same host, that host is assumed to be blocking TVs and every later logo
 * from it skips the pointless direct attempt.
 *
 * Requests are also paced: a couple in flight at a time, spaced apart, in DOM
 * order — which for a horizontal rail means the tiles the user can actually
 * see are fetched first. That is politeness toward the CDN rather than a fix
 * for imgur, and it keeps a 100-channel rail from opening 100 sockets at once
 * on a device with very little memory.
 *
 * Steady state costs nothing: image hosts send long cache lifetimes, so once
 * a logo has loaded the browser serves later launches from its own disk cache
 * without touching the network.
 */
var LogoLoader = (function () {
  // Deliberately small: the point is never to look like a burst.
  var MAX_CONCURRENT = 3;
  var MIN_SPACING_MS = 120;

  /* Attempt 0 is the logo's real URL. Every later attempt goes through the
   * CDN, so the delays here are short — the first retry is not waiting for
   * anything to recover, it is switching route. The last one is spaced out in
   * case the CDN itself is briefly unhappy. */
  var RETRY_DELAYS_MS = [300, 3000];

  var PROXY_PREFIX = 'https://imagecdn.app/v2/image/';
  // A rail tile is about 240px wide at 1080p, and the logo band is capped at
  // 78% of it, so there is nothing to gain from a larger source image.
  var PROXY_SUFFIX = '?width=240';

  // How many direct failures from one host before it is written off.
  var DIRECT_FAILURE_LIMIT = 3;

  var queue = [];
  var active = 0;
  var lastStartAt = 0;
  var pumpTimer = null;
  /* Bumped by reset(). A request already in flight cannot be recalled, so
   * its callbacks capture the generation they belong to and bail out rather
   * than decrementing a counter that has since been zeroed — which would
   * drive `active` negative and let the next rail exceed the concurrency
   * cap, the one thing the pacing exists to enforce. */
  var generation = 0;

  // host -> consecutive direct failures. Not persisted: three requests is a
  // cheap price to re-learn it, and a host that starts working again should
  // not stay written off for the life of an install.
  var directFailures = {};

  function now() {
    return Date.now ? Date.now() : new Date().getTime();
  }

  /* Hand-rolled rather than `new URL()`: that constructor is unavailable on
   * the older webOS engines this app still targets. */
  function hostOf(url) {
    var match = /^https?:\/\/([^/?#]+)/i.exec(url || '');
    return match ? match[1].toLowerCase() : '';
  }

  function isDirectBlocked(url) {
    return directFailures[hostOf(url)] >= DIRECT_FAILURE_LIMIT;
  }

  function proxied(url) {
    return PROXY_PREFIX + encodeURIComponent(url) + PROXY_SUFFIX;
  }

  /* Dropped on the floor when a rail is rebuilt: its <img> elements are
   * detached and loading them would paint nothing. */
  function reset() {
    generation++;
    queue = [];
    active = 0;
    if (pumpTimer) {
      clearTimeout(pumpTimer);
      pumpTimer = null;
    }
  }

  function enqueue(root) {
    if (!root || !root.querySelectorAll) return;
    var imgs = root.querySelectorAll('img[data-logo]');
    for (var i = 0; i < imgs.length; i++) {
      var img = imgs[i];
      // extend() re-scans the whole rail, so tiles already handled must not
      // be queued a second time.
      if (img.logoQueued) continue;
      img.logoQueued = true;
      img.logoAttempts = 0;
      queue.push(img);
    }
    pump();
  }

  function pump() {
    if (pumpTimer) return;
    if (!queue.length || active >= MAX_CONCURRENT) return;

    var wait = MIN_SPACING_MS - (now() - lastStartAt);
    if (wait > 0) {
      pumpTimer = setTimeout(function () {
        pumpTimer = null;
        pump();
      }, wait);
      return;
    }

    var img = queue.shift();
    // A tile can scroll out of the rail's rendered window while it waits.
    if (!img || !document.body.contains(img)) {
      pump();
      return;
    }

    start(img);
    pump();
  }

  function start(img) {
    var gen = generation;
    var url = img.getAttribute('data-logo');
    // Skip the direct attempt entirely once this host has proved it refuses
    // TVs — otherwise every one of a hundred logos pays for the same lesson.
    var direct = img.logoAttempts === 0 && !isDirectBlocked(url);

    active++;
    lastStartAt = now();

    img.onload = function () {
      img.onload = null;
      img.onerror = null;
      if (gen !== generation) return;
      active--;
      if (direct) directFailures[hostOf(url)] = 0;
      // Only now is the letter swapped out — the tile stays readable for the
      // whole time its logo is queued behind other requests.
      if (img.parentNode) img.parentNode.className = 'channel-card-media has-logo';
      pump();
    };

    img.onerror = function () {
      img.onload = null;
      img.onerror = null;
      if (gen !== generation) return;
      active--;

      if (direct) {
        var host = hostOf(url);
        directFailures[host] = (directFailures[host] || 0) + 1;
      }

      var delay = RETRY_DELAYS_MS[img.logoAttempts];
      img.logoAttempts++;

      if (delay === undefined) {
        // Out of routes: the placeholder letter is already on screen and
        // stays there, which is the correct end state for a dead URL.
        pump();
        return;
      }

      // Switching route (direct -> CDN) goes back to the *front* of the
      // queue: this tile is not being punished for a flaky host, it simply
      // needs a different URL, and it is near the front precisely because it
      // is one of the tiles on screen. Later retries go to the back, so a
      // genuinely dead URL cannot keep jumping the queue.
      var toFront = img.logoAttempts === 1;
      setTimeout(function () {
        if (gen !== generation) return;
        if (toFront) queue.unshift(img);
        else queue.push(img);
        pump();
      }, delay);
      pump();
    };

    img.src = direct ? url : proxied(url);
  }

  return { enqueue: enqueue, reset: reset };
})();
